### PR TITLE
deps: updated libdns/digitalocean dependency

### PR DESCRIPTION
**Pull request by mikemimik**
Updated the `libdns/digitalocean` dependency. This is a specific update to that dependency to pull in [upstream changes](https://github.com/libdns/digitalocean/commit/186c4ebd22152458b6ad018238dd2a92311a87d0). If you clone this repository and run `go get -u` you'll notice that a lot more updating happens. I have *not* included those updates in this PR as I think it's outside of the scope in which I intended for this PR. However, I think it might be good if that happened at some point. If you'd like me to include that in this PR I'd be more than happy to.

If this breaks something, or if I've overlooked something simple (I'm not a go developer) please let me know and I can address it in this PR or another.

Fixes: #3, #8

References:
- https://github.com/libdns/digitalocean/commit/186c4ebd22152458b6ad018238dd2a92311a87d0
- https://github.com/libdns/digitalocean/pull/3

### CODE REVIEW

**Comment by K1Z4** [comment]
Incase anyone is like me trying to get this working before the PR is merged. Here's what I did:

- Fork repo
- Apply changes from this PR
- Update the first line of go.mod to point to your forked repo
- `go clean -modcache`
- `go get github.com/K1Z4/digitalocean@ba0365b` (Replace my user with yours and update the SHA after the @ to your latest commit SHA)
- Build as usual but `--with` your own repo. e.g. `xcaddy build --with github.com/K1Z4/digitalocean`

**Comment by pixeye33** [comment]
Did not wanted to wait any longer also, here is my solution for a Docker version :)

```
FROM caddy:builder-alpine AS builder

RUN git clone https://github.com/caddy-dns/digitalocean my-caddy-dns && cd my-caddy-dns && git pull origin pull/9/head

RUN xcaddy build --with github.com/caddy-dns/digitalocean=$PWD/my-caddy-dns

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by TheKnarf** [comment]
Any update on getting this merged in?

**Review by mholt — APPROVED** [review]
Taking administrative override on this one -- hope that's alright @SvenDowideit. (Thanks for building this module!)

**Pull request merged**
