### PR TITLE
Move replacer to Provisioning phase

### PR DESCRIPTION
**Pull request by francislavoie**
See https://github.com/caddy-dns/cloudflare/pull/19 for the explanation. This makes the replacer work for JSON configs, and makes sure the autosave.json doesn't leak the credentials.

### CODE REVIEW

**Comment by francislavoie** [comment]
FYI @SvenDowideit

**Comment by SvenDowideit** [comment]
nice! and a great way to become aware of new functionality :)

so this means we can update the README json example to 

```
{
	"module": "acme",
	"challenges": {
		"dns": {
			"provider": {
				"name": "digitalocean",
				"api_token": "{env.CLOUDFLARE_API_TOKEN}"
			}
		}
	}
}
```

**Comment by francislavoie** [comment]
Yeah - should be `{env.DIGITALOCEAN_API_TOKEN}` probably.

**Comment by SvenDowideit** [comment]
edited comment :)

**Comment by SvenDowideit** [comment]
gah! I don't use DO atm, and I haven't thought about how to test this :/

@francislavoie have you tested this with a DO domain - happy to merge if it works for you, but otherwise, I'll need to find a bit of time to build a test setup.

**Comment by francislavoie** [comment]
I have not, I don't use DO. But I've made exactly the same PR on every other caddy-dns plugin. Most of them merged already.

**Comment by SvenDowideit** [comment]
yeah - I'm basically feeling the guilts for not building some kind of automated test harness for this repo :/

I guess I'll cave to peer pressure, cos I don't really have time to build it in the next few days :)

**Comment by francislavoie** [comment]
:sweat_smile: 

I don't think any of the DNS plugins have tests, because realistically it's not that viable, since it needs to run against a real API to validate that it works, unless the DNS service has a staging/mock service.

**Pull request merged**
